apiVersion: v1
kind: Service
metadata:
  name: fund
  labels:
    app: fund
    tier: backend
spec:
  #type: Cluster IP is a default service
  selector:
    app: fund
  ports:
    - name: http
      port: 8080 # ClusterIp Service Port
      targetPort: 8080 # Container Port
